name: Mirror to Bitbucket Repo

on: [ push, delete, create ]

# 确保一次只运行一个镜像任务。
concurrency:
  group: git-mirror
  
jobs: 
  git-mirror: 
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 1、github 代码同步到 gitee 的仓库
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:bealei/bealei.github.io.git"
          # 注意替换为你的 Gitee 目标仓库地址.
          destination-repo: "git@gitee.com:bealei/bealei.git"