# 工作流名字
name: github -- Gitee
# 触发条件
on:

  push:
    branches: ["master","main"]

  # schedule:
  #   # 定时任务，在每天的24点 18点推送签到信息到邮箱
  #   - cron:  0 16 * * * 

  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:


# 设置GITHUB_TOKEN的权限以允许部署到GITHUB页面
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一次并发部署，跳过在进行中的运行和最近排队的运行之间排队的运行。
# 但是，不要取消正在进行的运行，因为我们希望完成这些生产部署。
concurrency:
  group: "pages"
  cancel-in-progress: false
# 任务
jobs:

  
  deploy: # 单一部署作业，因为我们只是在部署
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout  # 检验
        uses: actions/checkout@v3     
      - name: Setup Pages # 设置页面
        uses: actions/configure-pages@v3        
      - name: Upload artifact # 上传工件
        uses: actions/upload-pages-artifact@v2
        with:
          # 部署的指定文件夹
          path: 'docs'
          # 上传整个存储库
          # path: '.'
      - name: Deploy to GitHub Pages  # 部署到GitHub页面
        id: deployment
        uses: actions/deploy-pages@v2
 


        
  build:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    # 步骤
    steps:

      # 1、github 代码同步到 gitee 的仓库
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:bealei/bealei.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址.
          destination-repo: git@gitee.com:bealei/bealei.git

      # 2、部署到 Gitee Page
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: bealei
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: bealei/bealei
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: master
          # 要部署的分支上的目录（默认是根目录root）
          directory: /docs